# Generated by Django 4.1.6 on 2023-02-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TblCliente",
            fields=[
                (
                    "id_cliente",
                    models.BigIntegerField(
                        db_column="Id_Cliente", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(db_column="Nombre", max_length=100)),
                ("direccion", models.CharField(db_column="Direccion", max_length=200)),
                ("telefono1", models.CharField(db_column="Telefono1", max_length=20)),
                ("telefono2", models.CharField(db_column="Telefono2", max_length=20)),
                (
                    "correo_electronico",
                    models.CharField(db_column="Correo_Electronico", max_length=100),
                ),
                ("fecha", models.DateTimeField(db_column="Fecha")),
                ("identidad", models.CharField(db_column="Identidad", max_length=100)),
                ("rtn", models.CharField(db_column="RTN", max_length=100)),
                (
                    "descripcion",
                    models.CharField(db_column="Descripcion", max_length=1000),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fceha_creacion", models.DateTimeField(db_column="Fceha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_cliente",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblClienteTipo",
            fields=[
                (
                    "id_tipocliente",
                    models.BigIntegerField(
                        db_column="Id_TipoCliente", primary_key=True, serialize=False
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(db_column="Descripcion", max_length=1000),
                ),
                ("estado", models.CharField(db_column="Estado", max_length=45)),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fceha_modificacion",
                    models.DateTimeField(db_column="Fceha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_cliente_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblCompra",
            fields=[
                (
                    "id_compra",
                    models.BigIntegerField(
                        db_column="Id_Compra", primary_key=True, serialize=False
                    ),
                ),
                (
                    "total_compras",
                    models.DecimalField(
                        db_column="Total_Compras", decimal_places=0, max_digits=10
                    ),
                ),
                ("fecha", models.DateTimeField(db_column="Fecha")),
                ("impuesto", models.DateTimeField(db_column="Impuesto")),
                ("descripcion", models.CharField(max_length=1000)),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_compra",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblCompraDetalle",
            fields=[
                (
                    "id_compra_detalle",
                    models.BigIntegerField(
                        db_column="Id_Compra_Detalle", primary_key=True, serialize=False
                    ),
                ),
                ("cantidad", models.FloatField(db_column="Cantidad")),
                (
                    "impuesto",
                    models.DecimalField(
                        db_column="Impuesto", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "precio_compra",
                    models.DecimalField(
                        db_column="Precio_Compra", decimal_places=0, max_digits=10
                    ),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.CharField(db_column="Fecha_Modificacion", max_length=45),
                ),
            ],
            options={
                "db_table": "tbl_compra_detalle",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblHistContrasea",
            fields=[
                (
                    "id_hist",
                    models.BigIntegerField(
                        db_column="Id_Hist", primary_key=True, serialize=False
                    ),
                ),
                (
                    "contrasena",
                    models.CharField(db_column="Contraseña", max_length=100),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_hist_contraseña",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblKardex",
            fields=[
                (
                    "id_kardex",
                    models.BigIntegerField(
                        db_column="Id_Kardex", primary_key=True, serialize=False
                    ),
                ),
                ("cantidad", models.FloatField(db_column="Cantidad")),
                ("fecha", models.DateTimeField(db_column="Fecha")),
                ("hora", models.TimeField(db_column="Hora")),
                (
                    "descripcion",
                    models.CharField(db_column="Descripcion", max_length=1000),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_kardex",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblKardexTipoMovimiento",
            fields=[
                (
                    "id_tipomovimiento",
                    models.BigIntegerField(
                        db_column="Id_TipoMovimiento", primary_key=True, serialize=False
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(db_column="Descripcion", max_length=1000),
                ),
                ("estado", models.CharField(db_column="Estado", max_length=45)),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_kardex_tipo_movimiento",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblMsBitacora",
            fields=[
                (
                    "id_bitacora",
                    models.BigIntegerField(
                        db_column="Id_Bitacora", primary_key=True, serialize=False
                    ),
                ),
                ("fecha", models.DateTimeField(db_column="Fecha")),
                ("accion", models.CharField(db_column="Accion", max_length=20)),
                (
                    "descripcion",
                    models.CharField(db_column="Descripcion", max_length=1000),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_ms_bitacora",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblMsObjetos",
            fields=[
                (
                    "id_objeto",
                    models.BigIntegerField(
                        db_column="Id_Objeto", primary_key=True, serialize=False
                    ),
                ),
                ("objeto", models.CharField(db_column="Objeto", max_length=100)),
                (
                    "descripcion",
                    models.CharField(db_column="Descripcion", max_length=1000),
                ),
                (
                    "tipo_objeto",
                    models.CharField(db_column="Tipo_Objeto", max_length=45),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_ms_objetos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblMsParametros",
            fields=[
                (
                    "id_parametro",
                    models.BigIntegerField(
                        db_column="Id_Parametro", primary_key=True, serialize=False
                    ),
                ),
                ("parametro", models.CharField(db_column="Parametro", max_length=50)),
                ("valor", models.CharField(db_column="Valor", max_length=100)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_ms_parametros",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblMsPermisos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "permiso_insercion",
                    models.CharField(db_column="Permiso_Insercion", max_length=1),
                ),
                (
                    "permiso_eliminacion",
                    models.CharField(db_column="Permiso_Eliminacion", max_length=1),
                ),
                (
                    "permiso_actualizacion",
                    models.CharField(db_column="Permiso_Actualizacion", max_length=1),
                ),
                (
                    "permiso_consultar",
                    models.CharField(db_column="Permiso_Consultar", max_length=1),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_ms_permisos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblMsPreguntas",
            fields=[
                (
                    "id_pregunta",
                    models.BigIntegerField(
                        db_column="Id_Pregunta", primary_key=True, serialize=False
                    ),
                ),
                ("pregunta", models.CharField(db_column="Pregunta", max_length=100)),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_ms_preguntas",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblMsPreguntasUsuario",
            fields=[
                (
                    "id_pregunta_usuario",
                    models.BigIntegerField(
                        db_column="Id_Pregunta_Usuario",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("respuesta", models.CharField(db_column="Respuesta", max_length=100)),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_ms_preguntas_usuario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblMsRoles",
            fields=[
                (
                    "id_rol",
                    models.BigIntegerField(
                        db_column="Id_Rol", primary_key=True, serialize=False
                    ),
                ),
                ("rol", models.CharField(db_column="Rol", max_length=30)),
                (
                    "descripcion",
                    models.CharField(db_column="Descripcion", max_length=1000),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_ms_roles",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblMsUsuario",
            fields=[
                (
                    "id_usuario",
                    models.BigIntegerField(
                        db_column="Id_Usuario", primary_key=True, serialize=False
                    ),
                ),
                ("usuario", models.CharField(db_column="Usuario", max_length=15)),
                (
                    "nombre_usuario",
                    models.CharField(db_column="Nombre_Usuario", max_length=100),
                ),
                (
                    "estado_usuario",
                    models.CharField(db_column="Estado_Usuario", max_length=100),
                ),
                (
                    "contrasena",
                    models.CharField(db_column="Contraseña", max_length=100),
                ),
                (
                    "fecha_ultima_conexion",
                    models.DateTimeField(db_column="Fecha_Ultima_Conexion"),
                ),
                ("primer_ingreso", models.BigIntegerField(db_column="Primer_Ingreso")),
                (
                    "fecha_vencimiento",
                    models.DateTimeField(db_column="Fecha_Vencimiento"),
                ),
                (
                    "correo_electronico",
                    models.CharField(db_column="Correo_Electronico", max_length=50),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
                (
                    "preguntas_contestadas",
                    models.CharField(db_column="Preguntas_Contestadas", max_length=45),
                ),
            ],
            options={
                "db_table": "tbl_ms_usuario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblProducto",
            fields=[
                (
                    "id_producto",
                    models.BigIntegerField(
                        db_column="Id_Producto", primary_key=True, serialize=False
                    ),
                ),
                (
                    "nombre_producto",
                    models.CharField(db_column="Nombre_Producto", max_length=100),
                ),
                ("cantidad", models.FloatField(db_column="Cantidad")),
                ("cantidad_maxima", models.FloatField(db_column="Cantidad_Maxima")),
                ("cantidad_minima", models.FloatField(db_column="Cantidad_Minima")),
                ("unidad_medida", models.FloatField(db_column="Unidad_Medida")),
                (
                    "descripcion",
                    models.CharField(db_column="Descripcion", max_length=1000),
                ),
                (
                    "excento_impuesto",
                    models.CharField(db_column="Excento_Impuesto", max_length=45),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_producto",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblProductoProduccion",
            fields=[
                (
                    "id_producto_produccion",
                    models.BigIntegerField(
                        db_column="Id_Producto_Produccion",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("fecha", models.DateTimeField(db_column="Fecha")),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_producto_produccion",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblProductoTerminadoDetalle",
            fields=[
                (
                    "id_producto_terminado_detalle",
                    models.BigIntegerField(
                        db_column="Id_Producto_Terminado_Detalle",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("cantidad", models.FloatField(db_column="Cantidad")),
                ("fecha", models.DateTimeField(db_column="Fecha")),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_producto_terminado_detalle",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblProductoTipo",
            fields=[
                (
                    "id_tipoproducto",
                    models.BigIntegerField(
                        db_column="Id_TipoProducto", primary_key=True, serialize=False
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(db_column="Descripcion", max_length=1000),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_producto_tipo",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblProveedores",
            fields=[
                (
                    "id_proveedor",
                    models.BigIntegerField(
                        db_column="Id_Proveedor", primary_key=True, serialize=False
                    ),
                ),
                ("nombre", models.CharField(db_column="Nombre", max_length=50)),
                (
                    "descripcion",
                    models.CharField(db_column="Descripcion", max_length=1000),
                ),
                (
                    "telefono_empresa",
                    models.CharField(db_column="Telefono_Empresa", max_length=45),
                ),
                (
                    "telefono_encargado",
                    models.CharField(db_column="Telefono_Encargado", max_length=45),
                ),
                (
                    "correo_electronico",
                    models.CharField(db_column="Correo_Electronico", max_length=45),
                ),
                ("direccion", models.CharField(db_column="Direccion", max_length=50)),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_proveedores",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblTalonarioCai",
            fields=[
                (
                    "id_talonario",
                    models.BigIntegerField(
                        db_column="Id_Talonario", primary_key=True, serialize=False
                    ),
                ),
                ("factura", models.CharField(db_column="Factura", max_length=100)),
                (
                    "secuencia_actual",
                    models.CharField(db_column="Secuencia_Actual", max_length=50),
                ),
                (
                    "secuencia_inicial",
                    models.CharField(db_column="Secuencia_Inicial", max_length=50),
                ),
                (
                    "secuencia_final",
                    models.CharField(db_column="Secuencia_Final", max_length=50),
                ),
                (
                    "fecha_vencimiento",
                    models.DateTimeField(db_column="Fecha_Vencimiento"),
                ),
                ("numero_cai", models.IntegerField(db_column="Numero_Cai")),
                ("sucursal", models.CharField(db_column="Sucursal", max_length=45)),
                (
                    "punto_emision",
                    models.CharField(db_column="Punto_Emision", max_length=45),
                ),
                (
                    "tipo_documento",
                    models.CharField(db_column="Tipo_Documento", max_length=45),
                ),
                ("estado", models.CharField(db_column="Estado", max_length=45)),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_talonario_cai",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblVenta",
            fields=[
                (
                    "id_venta",
                    models.BigIntegerField(
                        db_column="Id_Venta", primary_key=True, serialize=False
                    ),
                ),
                ("fecha", models.DateTimeField(db_column="Fecha")),
                (
                    "sub_total",
                    models.DecimalField(
                        db_column="Sub_Total", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        db_column="Descuento", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "impuesto",
                    models.DecimalField(
                        db_column="Impuesto", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "total_pagar",
                    models.DecimalField(
                        db_column="Total_Pagar", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(db_column="Descripcion", max_length=1000),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_venta",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblVentaDetalle",
            fields=[
                (
                    "id_venta_detalle",
                    models.BigIntegerField(
                        db_column="Id_venta_detalle", primary_key=True, serialize=False
                    ),
                ),
                ("cantidad", models.FloatField(db_column="Cantidad")),
                (
                    "sub_total",
                    models.DecimalField(
                        db_column="Sub_Total", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "descuento",
                    models.DecimalField(
                        db_column="Descuento", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "impuesto",
                    models.DecimalField(
                        db_column="Impuesto", decimal_places=0, max_digits=10
                    ),
                ),
                (
                    "total_pagar",
                    models.DecimalField(
                        db_column="Total_Pagar", decimal_places=0, max_digits=10
                    ),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_venta_detalle",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblVentaEstado",
            fields=[
                (
                    "id_ventaestado",
                    models.BigIntegerField(
                        db_column="Id_VentaEstado", primary_key=True, serialize=False
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(db_column="Descripcion", max_length=1000),
                ),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_venta_estado",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="TblVentaTipoPago",
            fields=[
                (
                    "id_tipopago",
                    models.BigIntegerField(
                        db_column="Id_TipoPago", primary_key=True, serialize=False
                    ),
                ),
                (
                    "descripcion",
                    models.CharField(db_column="Descripcion", max_length=100),
                ),
                ("estado", models.CharField(db_column="Estado", max_length=45)),
                ("creado_por", models.CharField(db_column="Creado_Por", max_length=15)),
                ("fecha_creacion", models.DateTimeField(db_column="Fecha_Creacion")),
                (
                    "modificado_por",
                    models.CharField(db_column="Modificado_Por", max_length=15),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(db_column="Fecha_Modificacion"),
                ),
            ],
            options={
                "db_table": "tbl_venta_tipo_pago",
                "managed": False,
            },
        ),
    ]
